import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header1 from "@/components/Header1";
import Footer1 from "@/components/Footer1";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartProvider } from "@/components/CartContext";
import { ChakraProvider} from '@chakra-ui/react';  
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
      <ChakraProvider> 
      <Header1/>
      <Header/>
      <hr className="mt-4"/>
       {children}
      <Footer1/>
      <Footer/>
      </ChakraProvider>
      </body>
    </html>
  );
}