import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header1 from "@/components/Header1";
import Footer1 from "@/components/Footer1";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header1 />
      <Header />
        <hr className="my-3"/>
        {children}
      <Footer1 />
      <Footer />
      </body>
    </html>
  );
}
